/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ArtifactsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "DownloadDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "DownloadQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "GifDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "GifQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Mp3DLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Mp3Queue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "TrimDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "TrimQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "TrimtokTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "WsApi": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}