import { TERMINAL_WITH_ARTIFACT } from "../../jobs/domain/job-status.js";
import type { IConnectionRepository } from "./ports/connection.repository.js";
import type { IWebSocketAdapter } from "./ports/websocket.port.js";
import type { IJobReader } from "./ports/job-reader.port.js";

export interface INotifyJobUpdateUseCase {
  execute(jobId: string): Promise<void>;
}

export class NotifyJobUpdateUseCase implements INotifyJobUpdateUseCase {
  constructor(
    private readonly connRepo: IConnectionRepository,
    private readonly wsAdapter: IWebSocketAdapter,
    private readonly jobReader: IJobReader,
  ) {}

  async execute(jobId: string): Promise<void> {
    const job = await this.jobReader.findById(jobId);
    if (!job) return;

    const connections = await this.connRepo.findByJobId(jobId);
    if (connections.length === 0) return;

    const payload: Record<string, unknown> = {
      type: "job_update",
      jobId,
      status: job.status,
      title: job.title,
      duration: job.duration,
      thumbnailUrl: job.thumbnailUrl,
      updatedAt: job.updatedAt,
    };

    if (job.s3Key && TERMINAL_WITH_ARTIFACT.has(job.status)) {
      // downloadUrl is generated by calling code if needed; here we signal artifact is ready
      payload.s3Key = job.s3Key;
    }
    if (job.errorMessage) payload.errorMessage = job.errorMessage;

    await Promise.allSettled(
      connections.map(async (conn) => {
        try {
          await this.wsAdapter.send(conn.connectionId, payload);
        } catch (err: unknown) {
          // GoneException — stale connection, clean up
          const isGone =
            err instanceof Error &&
            (err.message.includes("GoneException") || err.message.includes("410"));
          if (isGone) {
            await this.connRepo.delete(conn.connectionId).catch(() => { /* best-effort */ });
          }
        }
      }),
    );
  }
}
